name: Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-13
    name: Run test suite
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: swift build
    - name: Run unit tests
      run: swift test --vv --parallel
