name: Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-11
    name: Test iOS
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild build-for-testing -scheme APUtils -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' | xcpretty && exit ${PIPESTATUS[0]}
