name: Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-11
    name: Test iOS
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: swift test --enable-code-coverage
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
